
import os

SQL_ALCHEMY_DATABASE_URI= '{CONFIGURE TU DB AQUI}' 



SQL_ALCHEMY_DROP_CREATE_DB_ON_RUN = False
SQL_ALCHEMY_CREATE_DEMO_DATASET = True

FLASK_LISTEN_PORT = "8080"
FLASK_ENDPOINT = "0.0.0.0"

APP_USER_AUTHORIZATION_FILTER = False
DEBUG_MODE = True
DEMO_MODE = True
